using namespace std;
static std::string input_series;
extern int seg_length;
extern int init_buffer;
extern vector <int> video_num;
extern vector<vector<int>> video_series;
extern vector<vector<vector<float>>> probs;
extern vector<vector<double>> brs;
extern vector<vector<double>> dists;
extern vector<vector<vector<double>>> video_size;
extern vector<vector<vector<float>>> pred_info;
extern vector<vector<vector<float>>> gt_info;
extern vector <string> video_names;
extern vector<vector<int>> user_info;
extern std::string tile_col, tile_row;
extern int tile_num;
extern float rho;
extern std::string experiment_dir;
extern std::string feature_dir;
extern std::string video_info_dir;
extern std::string prob_dir;
extern std::string prob_overall_dir;
extern std::string user_info_file;
extern std::string area_dir;
extern int M;
extern std::string cur_pre;

